export const DEPARTMENTS = [
  "Computer Science",
  "Information Technology",
  "Artificial Intelligence",
  "Data Science",
  "Cyber Security"
];

export const SEMESTERS = [1, 2, 3, 4, 5, 6, 7, 8];
export const DIVISIONS = ["A", "B", "C"];

export const INITIAL_STUDENTS = [
  {
    id: "STU-2024-001",
    rollNo: "CS2401",
    name: "Aarav Sharma",
    avatar: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80",
    email: "aarav.sharma@institution.edu",
    department: "Computer Science",
    semester: 6,
    division: "A",
    attendance: 94.5,
    avgMarks: 91.2,
    gpa: 3.92,
    predictedGpa: 3.95,
    predictedGrade: "A+",
    riskLevel: "Low",
    status: "Active",
    guardianName: "Rajesh Sharma",
    guardianPhone: "+91 98765 43210",
    subjectMarks: {
      "Data Structures": { assignment: 19, internal: 28, practical: 19, finalExam: 92, total: 93, grade: "A+" },
      "Machine Learning": { assignment: 20, internal: 29, practical: 20, finalExam: 95, total: 96, grade: "A+" },
      "Database Systems": { assignment: 18, internal: 27, practical: 18, finalExam: 88, total: 89, grade: "A" },
      "Web Architecture": { assignment: 19, internal: 28, practical: 19, finalExam: 90, total: 91, grade: "A+" }
    },
    attendanceHistory: [92, 95, 94, 96, 93, 95],
    gpaHistory: [3.85, 3.88, 3.90, 3.92],
    aiRecommendation: "Excellent academic trajectory. Recommended for advanced AI research project honors.",
    skills: { coding: 95, theory: 90, lab: 96, aptitude: 92, projects: 94, softSkills: 88 }
  },
  {
    id: "STU-2024-002",
    rollNo: "AI2405",
    name: "Rohan Varma",
    avatar: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80",
    email: "rohan.v@institution.edu",
    department: "Artificial Intelligence",
    semester: 6,
    division: "B",
    attendance: 64.0,
    avgMarks: 52.4,
    gpa: 2.15,
    predictedGpa: 1.95,
    predictedGrade: "F",
    riskLevel: "Critical",
    status: "At Risk",
    guardianName: "Sanjay Varma",
    guardianPhone: "+91 98123 45678",
    subjectMarks: {
      "Neural Networks": { assignment: 12, internal: 14, practical: 12, finalExam: 48, total: 51, grade: "D" },
      "Deep Learning": { assignment: 10, internal: 12, practical: 11, finalExam: 42, total: 46, grade: "F" },
      "Computer Vision": { assignment: 13, internal: 16, practical: 14, finalExam: 55, total: 58, grade: "C" },
      "Python Advanced": { assignment: 14, internal: 15, practical: 13, finalExam: 52, total: 54, grade: "D" }
    },
    attendanceHistory: [78, 72, 68, 65, 62, 64],
    gpaHistory: [2.80, 2.50, 2.30, 2.15],
    aiRecommendation: "High academic drop risk detected. Severe attendance drop in Deep Learning. Immediate counseling required.",
    skills: { coding: 55, theory: 48, lab: 52, aptitude: 50, projects: 58, softSkills: 60 }
  },
  {
    id: "STU-2024-003",
    rollNo: "DS2412",
    name: "Ananya Iyer",
    avatar: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150&auto=format&fit=crop&q=80",
    email: "ananya.i@institution.edu",
    department: "Data Science",
    semester: 6,
    division: "A",
    attendance: 91.0,
    avgMarks: 88.5,
    gpa: 3.80,
    predictedGpa: 3.85,
    predictedGrade: "A+",
    riskLevel: "Low",
    status: "Active",
    guardianName: "M. K. Iyer",
    guardianPhone: "+91 97654 32109",
    subjectMarks: {
      "Big Data Tools": { assignment: 18, internal: 27, practical: 19, finalExam: 89, total: 90, grade: "A+" },
      "Statistical Models": { assignment: 19, internal: 28, practical: 18, finalExam: 87, total: 88, grade: "A" },
      "Data Mining": { assignment: 18, internal: 26, practical: 19, finalExam: 86, total: 87, grade: "A" },
      "Cloud Analytics": { assignment: 19, internal: 28, practical: 19, finalExam: 88, total: 89, grade: "A" }
    },
    attendanceHistory: [90, 89, 92, 91, 93, 91],
    gpaHistory: [3.70, 3.75, 3.78, 3.80],
    aiRecommendation: "Consistent high performance across statistical and practical modules.",
    skills: { coding: 88, theory: 92, lab: 90, aptitude: 95, projects: 91, softSkills: 94 }
  },
  {
    id: "STU-2024-004",
    rollNo: "IT2408",
    name: "Vikram Patel",
    avatar: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80",
    email: "vikram.p@institution.edu",
    department: "Information Technology",
    semester: 6,
    division: "B",
    attendance: 72.5,
    avgMarks: 61.8,
    gpa: 2.65,
    predictedGpa: 2.50,
    predictedGrade: "C",
    riskLevel: "Medium",
    status: "Needs Support",
    guardianName: "Dinesh Patel",
    guardianPhone: "+91 98989 12345",
    subjectMarks: {
      "Network Security": { assignment: 14, internal: 18, practical: 15, finalExam: 62, total: 64, grade: "C" },
      "Cloud Infrastructure": { assignment: 15, internal: 19, practical: 14, finalExam: 58, total: 60, grade: "C" },
      "Web Frameworks": { assignment: 16, internal: 20, practical: 16, finalExam: 65, total: 67, grade: "B" },
      "Software Testing": { assignment: 13, internal: 15, practical: 13, finalExam: 54, total: 56, grade: "D" }
    },
    attendanceHistory: [75, 74, 73, 71, 70, 72.5],
    gpaHistory: [2.90, 2.80, 2.70, 2.65],
    aiRecommendation: "Attendance below recommended 75% threshold. Needs remediation in Software Testing.",
    skills: { coding: 68, theory: 58, lab: 65, aptitude: 62, projects: 70, softSkills: 64 }
  },
  {
    id: "STU-2024-005",
    rollNo: "CY2403",
    name: "Priya Nair",
    avatar: "https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=150&auto=format&fit=crop&q=80",
    email: "priya.nair@institution.edu",
    department: "Cyber Security",
    semester: 6,
    division: "A",
    attendance: 96.0,
    avgMarks: 94.8,
    gpa: 3.98,
    predictedGpa: 4.00,
    predictedGrade: "A+",
    riskLevel: "Low",
    status: "Active",
    guardianName: "Raman Nair",
    guardianPhone: "+91 97111 22334",
    subjectMarks: {
      "Ethical Hacking": { assignment: 20, internal: 30, practical: 20, finalExam: 96, total: 97, grade: "A+" },
      "Cryptography": { assignment: 19, internal: 29, practical: 19, finalExam: 94, total: 95, grade: "A+" },
      "Forensics": { assignment: 20, internal: 28, practical: 20, finalExam: 92, total: 93, grade: "A+" },
      "Malware Analysis": { assignment: 19, internal: 29, practical: 19, finalExam: 93, total: 94, grade: "A+" }
    },
    attendanceHistory: [95, 96, 97, 96, 96, 96],
    gpaHistory: [3.95, 3.96, 3.97, 3.98],
    aiRecommendation: "Rank 1 candidate in Cyber Security department. Outstanding ethical hacking lab scores.",
    skills: { coding: 98, theory: 94, lab: 99, aptitude: 96, projects: 97, softSkills: 92 }
  },
  {
    id: "STU-2024-006",
    rollNo: "CS2419",
    name: "Kabir Mehta",
    avatar: "https://images.unsplash.com/photo-1522075469751-3a6694fb2f61?w=150&auto=format&fit=crop&q=80",
    email: "kabir.m@institution.edu",
    department: "Computer Science",
    semester: 6,
    division: "C",
    attendance: 68.0,
    avgMarks: 58.0,
    gpa: 2.30,
    predictedGpa: 2.10,
    predictedGrade: "D",
    riskLevel: "High",
    status: "At Risk",
    guardianName: "Sunil Mehta",
    guardianPhone: "+91 98222 33445",
    subjectMarks: {
      "Data Structures": { assignment: 14, internal: 15, practical: 13, finalExam: 52, total: 55, grade: "D" },
      "Machine Learning": { assignment: 12, internal: 14, practical: 12, finalExam: 48, total: 50, grade: "D" },
      "Database Systems": { assignment: 15, internal: 18, practical: 16, finalExam: 62, total: 64, grade: "C" },
      "Web Architecture": { assignment: 13, internal: 16, practical: 14, finalExam: 56, total: 58, grade: "C" }
    },
    attendanceHistory: [72, 70, 69, 67, 66, 68],
    gpaHistory: [2.60, 2.50, 2.40, 2.30],
    aiRecommendation: "Attendance anomaly detected in morning sessions. Recommended for academic intervention.",
    skills: { coding: 60, theory: 55, lab: 58, aptitude: 52, projects: 62, softSkills: 58 }
  },
  {
    id: "STU-2024-007",
    rollNo: "AI2402",
    name: "Sneha Reddi",
    avatar: "https://images.unsplash.com/photo-1517841905240-472988babdf9?w=150&auto=format&fit=crop&q=80",
    email: "sneha.r@institution.edu",
    department: "Artificial Intelligence",
    semester: 6,
    division: "A",
    attendance: 89.0,
    avgMarks: 84.2,
    gpa: 3.60,
    predictedGpa: 3.65,
    predictedGrade: "A",
    riskLevel: "Low",
    status: "Active",
    guardianName: "K. V. Reddi",
    guardianPhone: "+91 98333 44556",
    subjectMarks: {
      "Neural Networks": { assignment: 17, internal: 25, practical: 18, finalExam: 82, total: 84, grade: "A" },
      "Deep Learning": { assignment: 18, internal: 26, practical: 18, finalExam: 84, total: 85, grade: "A" },
      "Computer Vision": { assignment: 17, internal: 24, practical: 17, finalExam: 80, total: 82, grade: "A" },
      "Python Advanced": { assignment: 18, internal: 26, practical: 18, finalExam: 85, total: 86, grade: "A" }
    },
    attendanceHistory: [88, 89, 90, 89, 88, 89],
    gpaHistory: [3.50, 3.55, 3.58, 3.60],
    aiRecommendation: "Steady improvement in practical AI model implementation.",
    skills: { coding: 85, theory: 84, lab: 86, aptitude: 82, projects: 88, softSkills: 85 }
  },
  {
    id: "STU-2024-008",
    rollNo: "DS2409",
    name: "Tanya Sen",
    avatar: "https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?w=150&auto=format&fit=crop&q=80",
    email: "tanya.sen@institution.edu",
    department: "Data Science",
    semester: 6,
    division: "B",
    attendance: 87.5,
    avgMarks: 79.5,
    gpa: 3.35,
    predictedGpa: 3.42,
    predictedGrade: "B+",
    riskLevel: "Low",
    status: "Active",
    guardianName: "A. K. Sen",
    guardianPhone: "+91 98444 55667",
    subjectMarks: {
      "Big Data Tools": { assignment: 16, internal: 23, practical: 17, finalExam: 78, total: 80, grade: "A" },
      "Statistical Models": { assignment: 17, internal: 24, practical: 17, finalExam: 76, total: 78, grade: "B+" },
      "Data Mining": { assignment: 16, internal: 22, practical: 16, finalExam: 74, total: 76, grade: "B+" },
      "Cloud Analytics": { assignment: 17, internal: 25, practical: 17, finalExam: 80, total: 82, grade: "A" }
    },
    attendanceHistory: [86, 87, 88, 87, 88, 87.5],
    gpaHistory: [3.20, 3.25, 3.30, 3.35],
    aiRecommendation: "Good problem solving skills. Potential to move to A grade with extra focus on Statistics.",
    skills: { coding: 80, theory: 78, lab: 82, aptitude: 84, projects: 80, softSkills: 83 }
  }
];

export const DEPARTMENT_STATS = [
  { name: "Computer Science", avgMarks: 78.4, attendance: 89.2, totalStudents: 320, passRate: 95.5 },
  { name: "Information Technology", avgMarks: 74.2, attendance: 85.8, totalStudents: 280, passRate: 92.1 },
  { name: "Artificial Intelligence", avgMarks: 81.5, attendance: 91.0, totalStudents: 240, passRate: 96.8 },
  { name: "Data Science", avgMarks: 79.0, attendance: 88.5, totalStudents: 220, passRate: 94.0 },
  { name: "Cyber Security", avgMarks: 82.8, attendance: 92.4, totalStudents: 220, passRate: 97.2 }
];

export const INITIAL_NOTIFICATIONS = [
  { id: 1, title: "Attendance Threshold Warning", message: "3 students in AI Dept dropped below 75% attendance.", time: "10 mins ago", type: "warning", unread: true },
  { id: 2, title: "Mid-Term Marks Uploaded", message: "Prof. Sarah uploaded marks for Machine Learning (CS-A).", time: "1 hour ago", type: "info", unread: true },
  { id: 3, title: "AI Model Prediction Complete", message: "ML API successfully updated end-semester predictions for 1,280 students.", time: "3 hours ago", type: "success", unread: false },
  { id: 4, title: "Academic Audit Alert", message: "Semester 6 audit report is ready for Dean review.", time: "Yesterday", type: "info", unread: false }
];
